include(CheckCXXSourceCompiles)
include(CheckLibraryExists)

function(asio_define_options)
  if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(_asio_default_build ON)
  else()
    set(_asio_default_build OFF)
  endif()

  option(ASIO_BUILD_TESTS "Build Asio tests" "${_asio_default_build}")
  option(ASIO_BUILD_EXAMPLES "Build Asio examples" "${_asio_default_build}")
  option(ASIO_ENABLE_OPENSSL "Build SSL tests and examples when OpenSSL is available" ON)
  option(ASIO_USE_BOOST "Use Boost support instead of standalone Asio" OFF)
  option(ASIO_ENABLE_BOOST_COROUTINE "Build Boost.Coroutine based tests and examples" OFF)
  option(ASIO_DEFINE_WIN32_WINNT "Define _WIN32_WINNT for Asio consumers on Windows" ON)
endfunction()

function(asio_configure_dependencies)
  set(_asio_has_cxx11 FALSE)
  set(_asio_has_cxx14 FALSE)
  set(_asio_has_cxx17 FALSE)
  set(_asio_has_cxx20 FALSE)

  if(cxx_std_11 IN_LIST CMAKE_CXX_COMPILE_FEATURES)
    set(_asio_has_cxx11 TRUE)
  endif()
  if(cxx_std_14 IN_LIST CMAKE_CXX_COMPILE_FEATURES)
    set(_asio_has_cxx14 TRUE)
  endif()
  if(cxx_std_17 IN_LIST CMAKE_CXX_COMPILE_FEATURES)
    set(_asio_has_cxx17 TRUE)
  endif()
  if(cxx_std_20 IN_LIST CMAKE_CXX_COMPILE_FEATURES)
    set(_asio_has_cxx20 TRUE)
  endif()

  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU"
      AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS_EQUAL 6)
    set(_asio_has_cxx14 FALSE)
  endif()

  set(ASIO_HAS_CXX11 "${_asio_has_cxx11}" PARENT_SCOPE)
  set(ASIO_HAS_CXX14 "${_asio_has_cxx14}" PARENT_SCOPE)
  set(ASIO_HAS_CXX17 "${_asio_has_cxx17}" PARENT_SCOPE)
  set(ASIO_HAS_CXX20 "${_asio_has_cxx20}" PARENT_SCOPE)

  set(_asio_has_coroutines FALSE)
  if(_asio_has_cxx20)
    set(_asio_saved_required_flags "${CMAKE_REQUIRED_FLAGS}")
    set(CMAKE_REQUIRED_QUIET TRUE)
    if(MSVC)
      set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} /std:c++20")
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
      set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} -std=c++20")
    endif()
    check_cxx_source_compiles([=[
#if !defined(__has_include)
# error __has_include required
#endif
#if !__has_include(<coroutine>)
# error no coroutine header
#endif
#include <coroutine>
int main() { return 0; }
]=] ASIO_HAS_STD_COROUTINE)
    set(CMAKE_REQUIRED_FLAGS "${_asio_saved_required_flags}")
    if(ASIO_HAS_STD_COROUTINE)
      set(_asio_has_coroutines TRUE)
    endif()
  endif()
  set(ASIO_HAS_COROUTINES "${_asio_has_coroutines}" PARENT_SCOPE)

  set(_asio_has_openssl FALSE)
  if(ASIO_ENABLE_OPENSSL)
    find_package(OpenSSL QUIET)
    if(OpenSSL_FOUND)
      set(_asio_has_openssl TRUE)
    endif()
  endif()
  set(ASIO_HAS_OPENSSL "${_asio_has_openssl}" PARENT_SCOPE)

  set(_asio_has_boost_coroutine FALSE)
  set(_asio_boost_coroutine_libraries)
  if(ASIO_ENABLE_BOOST_COROUTINE)
    find_package(Boost QUIET COMPONENTS coroutine context thread chrono system)
    if(Boost_FOUND)
      set(_asio_has_boost_coroutine TRUE)
      foreach(_asio_boost_component IN ITEMS coroutine context thread chrono system)
        if(TARGET Boost::${_asio_boost_component})
          list(APPEND _asio_boost_coroutine_libraries Boost::${_asio_boost_component})
        endif()
      endforeach()
      if(NOT _asio_boost_coroutine_libraries)
        set(_asio_boost_coroutine_libraries ${Boost_LIBRARIES})
      endif()
    endif()
  endif()
  set(ASIO_HAS_BOOST_COROUTINE "${_asio_has_boost_coroutine}" PARENT_SCOPE)
  set(ASIO_BOOST_COROUTINE_LIBRARIES "${_asio_boost_coroutine_libraries}" PARENT_SCOPE)
endfunction()

function(asio_add_library)
  add_library(asio INTERFACE)
  add_library(asio::asio ALIAS asio)

  target_include_directories(asio INTERFACE
    "$<BUILD_INTERFACE:${asio_SOURCE_DIR}/include>")
  target_compile_features(asio INTERFACE cxx_std_11)

  if(ASIO_USE_BOOST)
    find_package(Boost REQUIRED)
    target_compile_definitions(asio INTERFACE
      ASIO_ENABLE_BOOST
      BOOST_CHRONO_HEADER_ONLY
      BOOST_CHRONO_DONT_PROVIDE_HYBRID_ERROR_HANDLING)
    if(TARGET Boost::headers)
      target_link_libraries(asio INTERFACE Boost::headers)
    elseif(TARGET Boost::boost)
      target_link_libraries(asio INTERFACE Boost::boost)
    elseif(Boost_INCLUDE_DIRS)
      target_include_directories(asio INTERFACE ${Boost_INCLUDE_DIRS})
    endif()
  else()
    target_compile_definitions(asio INTERFACE ASIO_STANDALONE)
  endif()

  if(WIN32)
    target_link_libraries(asio INTERFACE ws2_32 mswsock bcrypt)
    if(ASIO_DEFINE_WIN32_WINNT)
      target_compile_definitions(asio INTERFACE _WIN32_WINNT=0x0601)
    endif()
  else()
    find_package(Threads REQUIRED)
    target_link_libraries(asio INTERFACE Threads::Threads)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      check_library_exists(rt clock_gettime "" ASIO_HAS_LIBRT)
      if(ASIO_HAS_LIBRT)
        target_link_libraries(asio INTERFACE rt)
      endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "SunOS")
      target_link_libraries(asio INTERFACE socket nsl)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Haiku")
      target_link_libraries(asio INTERFACE network)
    endif()
  endif()
endfunction()

function(asio_read_automake_source_vars out_var makefile)
  file(READ "${makefile}" _asio_am_content)
  string(REPLACE "\r\n" "\n" _asio_am_content "${_asio_am_content}")
  string(REPLACE "\r" "\n" _asio_am_content "${_asio_am_content}")
  string(REGEX REPLACE "\\\\[ \t]*\n[ \t]*" " " _asio_am_content "${_asio_am_content}")

  string(REGEX MATCHALL "(^|\n)[ \t]*[A-Za-z0-9_]+_SOURCES[ \t]*=[^\n]*"
    _asio_am_source_lines "${_asio_am_content}")

  set(_asio_am_vars)
  foreach(_asio_am_line IN LISTS _asio_am_source_lines)
    string(REGEX REPLACE "^\n" "" _asio_am_line "${_asio_am_line}")
    if(_asio_am_line MATCHES "^[ \t]*([A-Za-z0-9_]+)_SOURCES[ \t]*=[ \t]*(.*)$")
      set(_asio_am_name "${CMAKE_MATCH_1}")
      set(_asio_am_sources "${CMAKE_MATCH_2}")
      string(STRIP "${_asio_am_sources}" _asio_am_sources)
      string(REGEX REPLACE "[ \t]+" ";" _asio_am_sources "${_asio_am_sources}")
      set(_asio_am_clean_sources)
      foreach(_asio_am_source IN LISTS _asio_am_sources)
        if(NOT _asio_am_source STREQUAL "")
          list(APPEND _asio_am_clean_sources "${_asio_am_source}")
        endif()
      endforeach()
      set("ASIO_AM_${_asio_am_name}_SOURCES" "${_asio_am_clean_sources}" PARENT_SCOPE)
      list(APPEND _asio_am_vars "${_asio_am_name}")
    endif()
  endforeach()

  list(REMOVE_DUPLICATES _asio_am_vars)
  set("${out_var}" "${_asio_am_vars}" PARENT_SCOPE)
endfunction()

function(asio_sources_to_absolute out_var base_dir)
  set(_asio_abs_sources)
  foreach(_asio_source IN LISTS ARGN)
    if(IS_ABSOLUTE "${_asio_source}")
      list(APPEND _asio_abs_sources "${_asio_source}")
    else()
      list(APPEND _asio_abs_sources "${base_dir}/${_asio_source}")
    endif()
  endforeach()
  set("${out_var}" "${_asio_abs_sources}" PARENT_SCOPE)
endfunction()

function(asio_make_target_suffix out_var source)
  string(REGEX REPLACE "\\.cpp$" "" _asio_suffix "${source}")
  string(REPLACE "\\" "/" _asio_suffix "${_asio_suffix}")
  string(REPLACE "/" "_" _asio_suffix "${_asio_suffix}")
  string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _asio_suffix "${_asio_suffix}")
  set("${out_var}" "${_asio_suffix}" PARENT_SCOPE)
endfunction()

function(asio_make_test_name out_var source)
  string(REGEX REPLACE "\\.cpp$" "" _asio_name "${source}")
  string(REPLACE "\\" "/" _asio_name "${_asio_name}")
  string(REPLACE "/" "." _asio_name "${_asio_name}")
  set("${out_var}" "asio.${_asio_name}" PARENT_SCOPE)
endfunction()

function(asio_add_common_executable target base_dir)
  asio_sources_to_absolute(_asio_abs_sources "${base_dir}" ${ARGN})
  add_executable("${target}" ${_asio_abs_sources})
  target_link_libraries("${target}" PRIVATE asio::asio)
endfunction()
