include(AsioHelpers)

function(asio_add_examples)
  _asio_add_example_group(cpp11 11)
  _asio_add_example_group(cpp14 14)
  _asio_add_example_group(cpp17 20)
  _asio_add_example_group(cpp20 20)
endfunction()

function(_asio_add_example_group standard_dir standard)
  if(standard EQUAL 11 AND NOT ASIO_HAS_CXX11)
    return()
  elseif(standard EQUAL 14 AND NOT ASIO_HAS_CXX14)
    return()
  elseif(standard EQUAL 20 AND NOT ASIO_HAS_CXX20)
    return()
  endif()

  set(_asio_examples_dir "${asio_SOURCE_DIR}/src/examples/${standard_dir}")
  set(_asio_makefile "${_asio_examples_dir}/Makefile.am")
  if(NOT EXISTS "${_asio_makefile}")
    return()
  endif()

  asio_read_automake_source_vars(_asio_example_vars "${_asio_makefile}")

  foreach(_asio_var IN LISTS _asio_example_vars)
    if(_asio_var STREQUAL "libasio_a")
      continue()
    endif()

    set(_asio_should_add TRUE)
    set(_asio_target_standard "${standard}")
    set(_asio_extra_libraries)
    set(_asio_sources_var "ASIO_AM_${_asio_var}_SOURCES")
    set(_asio_sources "${${_asio_sources_var}}")

    if(_asio_var MATCHES "^ssl_")
      if(NOT ASIO_HAS_OPENSSL)
        set(_asio_should_add FALSE)
      else()
        list(APPEND _asio_extra_libraries OpenSSL::SSL OpenSSL::Crypto)
      endif()
    elseif(_asio_var MATCHES "^spawn_")
      if(NOT ASIO_HAS_BOOST_COROUTINE)
        set(_asio_should_add FALSE)
      else()
        list(APPEND _asio_extra_libraries ${ASIO_BOOST_COROUTINE_LIBRARIES})
      endif()
    elseif(_asio_var MATCHES "^windows_")
      if(NOT WIN32)
        set(_asio_should_add FALSE)
      endif()
    elseif(_asio_var MATCHES "^(chat_posix_chat_client|fork_|local_|type_erasure_type_erasure)")
      if(WIN32)
        set(_asio_should_add FALSE)
      endif()
    endif()

    if(standard_dir STREQUAL "cpp17")
      if(NOT ASIO_HAS_COROUTINES)
        set(_asio_should_add FALSE)
      endif()
      set(_asio_target_standard 20)
    elseif((standard_dir STREQUAL "cpp11" OR standard_dir STREQUAL "cpp14")
        AND _asio_var MATCHES "^executors_(pipeline|priority_scheduler)$")
      if(NOT ASIO_HAS_CXX20)
        set(_asio_should_add FALSE)
      endif()
      set(_asio_target_standard 20)
    elseif(standard_dir STREQUAL "cpp20"
        AND _asio_var MATCHES "^(channels_|coroutines_|type_erasure_)")
      if(NOT ASIO_HAS_COROUTINES)
        set(_asio_should_add FALSE)
      endif()
      set(_asio_target_standard 20)
    endif()

    if(NOT _asio_should_add)
      continue()
    endif()

    list(GET _asio_sources 0 _asio_main_source)
    asio_make_target_suffix(_asio_target_suffix "${_asio_main_source}")
    set(_asio_target "asio_example_${standard_dir}_${_asio_target_suffix}")

    asio_add_common_executable("${_asio_target}" "${_asio_examples_dir}" ${_asio_sources})
    target_compile_features("${_asio_target}" PRIVATE "cxx_std_${_asio_target_standard}")
    if(_asio_extra_libraries)
      target_link_libraries("${_asio_target}" PRIVATE ${_asio_extra_libraries})
    endif()
  endforeach()
endfunction()
