include(AsioHelpers)

function(asio_add_tests)
  _asio_add_unit_tests()
  _asio_add_property_tests()
endfunction()

function(_asio_add_unit_tests)
  set(_asio_tests_dir "${asio_SOURCE_DIR}/src/tests")
  asio_read_automake_source_vars(_asio_unit_vars "${_asio_tests_dir}/Makefile.am")

  foreach(_asio_var IN LISTS _asio_unit_vars)
    if(NOT _asio_var MATCHES "^unit_")
      continue()
    endif()

    set(_asio_standard 11)
    set(_asio_should_add TRUE)
    set(_asio_extra_libraries)
    set(_asio_sources_var "ASIO_AM_${_asio_var}_SOURCES")
    set(_asio_sources "${${_asio_sources_var}}")

    if(_asio_var MATCHES "^unit_ssl_")
      if(NOT ASIO_HAS_OPENSSL)
        set(_asio_should_add FALSE)
      else()
        list(APPEND _asio_extra_libraries OpenSSL::SSL OpenSSL::Crypto)
      endif()
    elseif(_asio_var STREQUAL "unit_spawn")
      if(NOT ASIO_HAS_BOOST_COROUTINE)
        set(_asio_should_add FALSE)
      else()
        list(APPEND _asio_extra_libraries ${ASIO_BOOST_COROUTINE_LIBRARIES})
      endif()
    elseif(_asio_var STREQUAL "unit_experimental_promise")
      set(_asio_standard 20)
      if(NOT ASIO_HAS_CXX20)
        set(_asio_should_add FALSE)
      endif()
    elseif(_asio_var MATCHES "^unit_experimental_(awaitable_operators|co_composed|coro_)")
      set(_asio_standard 20)
      if(NOT ASIO_HAS_COROUTINES)
        set(_asio_should_add FALSE)
      endif()
    elseif(_asio_var MATCHES "^unit_experimental_")
      if(NOT ASIO_HAS_CXX11)
        set(_asio_should_add FALSE)
      endif()
    endif()

    if(NOT _asio_should_add)
      continue()
    endif()

    list(GET _asio_sources 0 _asio_main_source)
    asio_make_target_suffix(_asio_target_suffix "${_asio_main_source}")
    asio_make_test_name(_asio_test_name "${_asio_main_source}")
    set(_asio_target "asio_test_${_asio_target_suffix}")

    asio_add_common_executable("${_asio_target}" "${_asio_tests_dir}" ${_asio_sources})
    target_compile_features("${_asio_target}" PRIVATE "cxx_std_${_asio_standard}")
    target_compile_definitions("${_asio_target}" PRIVATE
      BOOST_ALL_NO_LIB
      ASIO_DISABLE_DEPRECATED_MSG)
    if(_asio_extra_libraries)
      target_link_libraries("${_asio_target}" PRIVATE ${_asio_extra_libraries})
    endif()
    add_test(NAME "${_asio_test_name}" COMMAND "${_asio_target}")
  endforeach()
endfunction()

function(_asio_add_property_tests)
  set(_asio_properties_dir "${asio_SOURCE_DIR}/src/tests/properties")
  asio_read_automake_source_vars(_asio_property_vars "${_asio_properties_dir}/Makefile.am")

  foreach(_asio_var IN LISTS _asio_property_vars)
    set(_asio_standard 11)
    set(_asio_should_add TRUE)
    set(_asio_sources_var "ASIO_AM_${_asio_var}_SOURCES")
    set(_asio_sources "${${_asio_sources_var}}")

    if(_asio_var MATCHES "^cpp11_")
      set(_asio_standard 11)
      if(NOT ASIO_HAS_CXX11)
        set(_asio_should_add FALSE)
      endif()
    elseif(_asio_var MATCHES "^cpp14_")
      set(_asio_standard 14)
      if(NOT ASIO_HAS_CXX14)
        set(_asio_should_add FALSE)
      endif()
    elseif(_asio_var MATCHES "^cpp03_")
      set(_asio_standard 11)
      if(NOT ASIO_HAS_CXX11)
        set(_asio_should_add FALSE)
      endif()
    else()
      set(_asio_should_add FALSE)
    endif()

    if(_asio_should_add AND MSVC AND _asio_var MATCHES "^cpp(11|14)_")
      if(NOT ASIO_HAS_CXX20)
        set(_asio_should_add FALSE)
      endif()
      set(_asio_standard 20)
    endif()

    if(NOT _asio_should_add)
      continue()
    endif()

    list(GET _asio_sources 0 _asio_main_source)
    asio_make_target_suffix(_asio_target_suffix "${_asio_main_source}")
    asio_make_test_name(_asio_test_name "${_asio_main_source}")
    set(_asio_target "asio_test_${_asio_target_suffix}")

    asio_add_common_executable("${_asio_target}" "${_asio_properties_dir}" ${_asio_sources})
    target_compile_features("${_asio_target}" PRIVATE "cxx_std_${_asio_standard}")
    target_compile_definitions("${_asio_target}" PRIVATE
      BOOST_ALL_NO_LIB
      ASIO_DISABLE_DEPRECATED_MSG)
    add_test(NAME "${_asio_test_name}" COMMAND "${_asio_target}")
  endforeach()
endfunction()
